### ISSUE TITLE
npm error: Unhandled 'error' event

### ISSUE THREAD

**Issue by sirex** [ManoSeimas/manoseimas.lt#169]
Not sure if this brakes something or not, but letting you know:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by chompomonim** [comment]
hmm. Could you check if any node process is still running on your machine on 3000?

**Comment by sirex** [comment]
Looks like running:

```
$ sudo netstat -tunlp | grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      32312/node      
```

**Comment by menesis** [comment]
This means that `webpack-server.js` is already running.

```
$ ps uxa | grep webpack
menesis  20874  0.0  0.0   4516   764 pts/18   S+   17:02   0:00 sh -c node webpack-server.js
menesis  20875 13.7  6.1 1388340 229064 pts/18 Sl+  17:02   0:09 node webpack-server.js
```

I simply
```
$ killall node
$ make run
```

I suspect that happens when there is a syntax error or something and django devserver stops.

**Comment by sirex** [comment]
@menesis thanks, yes indeed, killing node helped.
