### ISSUE TITLE
Problems running tests

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#180]
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make test
scripts/runtests.py
nosetests manoseimas --match ^[Tt]est --verbosity=2 --nocapture --nologcapture --all-modules --with-doctest --doctest-tests
Using existing test database for alias 'default' ('test_manoseimas')...
Operations to perform:
  Synchronize unmigrated apps: widget, test_utils, lobbyists, webpack_loader, staticfiles, messages, sitemaps, compressor, django_extensions, django_nose, rest_framework, haystack, thumbnail
  Apply all migrations: sessions, admin, manoseimas, compatibility_test, auth, sites, default, contenttypes, lazysignup, mps_v2, scrapy
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "bin/django", line 103, in <module>
    sys.exit(djangorecipe.binscripts.manage('manoseimas.settings.vagrant'))
  File "/home/vagrant/manoseimas/eggs/djangorecipe-2.1.2-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/vagrant/manoseimas/eggs/django_nose-1.4.3-py2.7.egg/django_nose/runner.py", line 403, in run_tests
    result = self.run_suite(nose_argv)
  File "/home/vagrant/manoseimas/eggs/django_nose-1.4.3-py2.7.egg/django_nose/runner.py", line 335, in run_suite
    addplugins=plugins_to_add)
  File "/home/vagrant/manoseimas/eggs/nose-1.3.7-py2.7.egg/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/vagrant/manoseimas/eggs/nose-1.3.7-py2.7.egg/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/vagrant/manoseimas/eggs/nose-1.3.7-py2.7.egg/nose/core.py", line 50, in run
    wrapper = self.config.plugins.prepareTest(test)
  File "/home/vagrant/manoseimas/eggs/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/vagrant/manoseimas/eggs/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/vagrant/manoseimas/eggs/django_nose-1.4.3-py2.7.egg/django_nose/plugin.py", line 82, in prepareTest
    self.old_names = self.runner.setup_databases()
  File "/home/vagrant/manoseimas/eggs/django_nose-1.4.3-py2.7.egg/django_nose/runner.py", line 590, in setup_databases
    return super(NoseTestSuiteRunner, self).setup_databases()
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/commands/migrate.py", line 226, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/auth/management/__init__.py", line 114, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/models/query.py", line 392, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/manoseimas/eggs/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/manoseimas/eggs/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xC4\\x97' for column 'name' at row 10")
make: *** [test] Error 1
vagrant@vagrant-ubuntu-trusty-64:/
```

Any ideas how to fix?

**Comment by sirex** [comment]
Test database have to be created with correct encoding:

https://github.com/ManoSeimas/manoseimas.lt/blob/new_test/HACKING.rst#running-tests

```
mysql -e 'DROP DATABASE IF EXISTS test_manoseimas; CREATE DATABASE test_manoseimas CHARSET=utf8;'
```
