### ISSUE TITLE
Getting 'list index out of range' while adding new voting :(

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#185]
http://www.lrs.lt/sip/portal.show?p_r=15275&p_k=1&p_a=sale_bals&p_bals_id=-23086

On console:
```
[02/Aug/2016 08:36:14] "GET /valdymas/jsi18n/ HTTP/1.1" 200 7331
Internal Server Error: /valdymas/scrapy/voting/add/
Traceback (most recent call last):
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py", line 1461, in changeform_view
    new_object = self.save_form(request, form, change=not add)
  File "/vagrant/manoseimas/scrapy/admin.py", line 32, in save_form
    return services.crawl_voting(source)
  File "/vagrant/manoseimas/scrapy/services.py", line 32, in crawl_voting
    items = list(spider.parse_person_votes(response))
  File "/vagrant/manoseimas/scrapy/spiders/sittings.py", line 421, in parse_person_votes
    hxs = HtmlXPathSelector(response).select(xpath)[0]
IndexError: list index out of range
```

Traceback:
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/valdymas/scrapy/voting/add/?_changelist_filters=_to_field%3Did%26_popup%3D1

Django Version: 1.8.5
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'social.apps.django_app.default',
 'sorl.thumbnail',
 'compressor',
 'haystack',
 'lazysignup',
 'manoseimas',
 'django_extensions',
 'test_utils',
 'django_nose',
 'manoseimas.mps_v2',
 'manoseimas.widget',
 'manoseimas.lobbyists',
 'manoseimas.compatibility_test',
 'manoseimas.scrapy',
 'rest_framework',
 'webpack_loader',
 'debug_toolbar')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')


Traceback:
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py" in wrapper
  616.                 return self.admin_site.admin_view(view)(*args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/sites.py" in inner
  233.             return view(request, *args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py" in add_view
  1516.         return self.changeform_view(request, None, form_url, extra_context)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/utils/decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "/home/vagrant/manoseimas/eggs/Django-1.8.5-py2.7.egg/django/contrib/admin/options.py" in changeform_view
  1461.                 new_object = self.save_form(request, form, change=not add)
File "/vagrant/manoseimas/scrapy/admin.py" in save_form
  32.         return services.crawl_voting(source)
File "/vagrant/manoseimas/scrapy/services.py" in crawl_voting
  32.     items = list(spider.parse_person_votes(response))
File "/vagrant/manoseimas/scrapy/spiders/sittings.py" in parse_person_votes
  421.         hxs = HtmlXPathSelector(response).select(xpath)[0]

Exception Type: IndexError at /valdymas/scrapy/voting/add/
Exception Value: list index out of range
```

**Comment by chompomonim** [comment]
@sirex Help please! Is it because LRS change voting page again or it's something on our side?

**Comment by sirex** [comment]
This is the same lrs.lt website update as before. But `sittings` spider is not updated to work with new lrs.lt website, I have updated only `mps` spider. For `sittings` if you change new URL to an old one, `sittings` spider should work.

For example (I did not tried it myself):

    http://www.lrs.lt/sip/portal.show?p_r=15275&p_k=1&p_a=sale_bals&p_bals_id=-23086 (new and does not work with our sittings spider)
    http://www3.lrs.lt/pls/inter/w5_sale_new.bals?p_bals_id=-23086 (old and supported by our sittings spider)

As you see, `p_bals_id` is the same in both URLs.

**Comment by chompomonim** [comment]
Thanks for info. Maybe then I will ask to enter and save in DB only bals_id, and not whole URL. This will solve problem for the future as well.

**Comment by chompomonim** [comment]
Works for now as suggested @sirex and will be event better solution after #188
