### ISSUE TITLE
scrapy crawl sittings fails with ResourceNotFound

### ISSUE THREAD

**Issue by mgedmin** [ManoSeimas/manoseimas.lt#59]
```
vagrant@vagrant-ubuntu-trusty-64: /vagrant [git:master=] $ bin/scrapy crawl sittings
Traceback (most recent call last):
  File "bin/scrapy", line 80, in <module>
    sys.exit(scrapy.cmdline.execute())
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/commands/crawl.py", line 58, in run
    spider = crawler.spiders.create(spname, **opts.spargs)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/spidermanager.py", line 48, in create
    return spcls(**spider_kwargs)
  File "/vagrant/manoseimas/scrapy/spiders/sittings.py", line 76, in __init__
    voting = get_sequential_votings(limit=1)[0]
  File "/vagrant/manoseimas/scrapy/db.py", line 114, in get_sequential_votings
    return list(RawVoting.view('scrapy/sequential_votings', **params))
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 1095, in __len__
    return self.count()
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 1018, in count
    self._fetch_if_needed()
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 1052, in _fetch_if_needed
    self.fetch()
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 1031, in fetch
    self._result_cache = self.fetch_raw().json_body
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 1048, in fetch_raw
    return self._fetch(self._arg, self.params)
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 723, in raw_view
    return self.res.get(view_path, **params)
  File "/vagrant/parts/restkit/restkit/resource.py", line 114, in get
    params_dict=params_dict, **params)
  File "/vagrant/parts/couchdbkit/couchdbkit/resource.py", line 129, in request
    response=e.response)
couchdbkit.exceptions.ResourceNotFound: missing
```

**Comment by mgedmin** [comment]
`bin/django syncsittings` fails in the same way.

**Comment by mgedmin** [comment]
AFAIU, this fails because my CouchDB lacks some views.  Specifically, `scrapy/sequential_votings` for `scrapy crawl sittings`, and `scrapy/sequential_votings_with_documents` for `django syncsittings`.

**Comment by mgedmin** [comment]
`bin/django syncsittings --update` works now (~2.5 minutes).
