### ISSUE TITLE
bin/scrapy crawl sittings fails with IndexError

### ISSUE THREAD

**Issue by mgedmin** [ManoSeimas/manoseimas.lt#72]
```
vagrant@vagrant-ubuntu-trusty-64: /vagrant [git:master=] $ bin/scrapy crawl sittings
Traceback (most recent call last):
  File "bin/scrapy", line 80, in <module>
    sys.exit(scrapy.cmdline.execute())
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/commands/crawl.py", line 58, in run
    spider = crawler.spiders.create(spname, **opts.spargs)
  File "/vagrant/eggs/Scrapy-0.24.6-py2.7.egg/scrapy/spidermanager.py", line 48, in create
    return spcls(**spider_kwargs)
  File "/vagrant/manoseimas/scrapy/spiders/sittings.py", line 76, in __init__
    voting = get_sequential_votings(limit=1)[0]
IndexError: list index out of range
```

**Comment by mgedmin** [comment]
`bin/django syncsittings --scrape` fails the same way.
