### ISSUE TITLE
/votings widget fails to work (AJAX request returns 500)

### ISSUE THREAD

**Issue by mgedmin** [ManoSeimas/manoseimas.lt#77]
Traceback:
```
Internal Server Error: /widget/data/voting/0002zr
Traceback (most recent call last):
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/manoseimas/decorators.py", line 32, in wrapper
    response = view_func(request, *args, **kwargs)
  File "/vagrant/manoseimas/widget/views.py", line 51, in voting_data
    content = Node.get_db().list("widget/voting-joined", "voting-objects", startkey=[slug], endkey=[slug, u'\ufff0'], include_docs=True)
  File "/vagrant/parts/couchdbkit/couchdbkit/client.py", line 410, in list
    return self.res.get(list_path, **params).json_body
  File "/vagrant/parts/restkit/restkit/resource.py", line 114, in get
    params_dict=params_dict, **params)
  File "/vagrant/parts/couchdbkit/couchdbkit/resource.py", line 129, in request
    response=e.response)
ResourceNotFound: missing
```

**Comment by mgedmin** [comment]
My CouchDB lacks these design documents, compared to the one used in production:

- nodes: _design/auth
- nodes: _design/widget

Everything else matches (but I didn't compare the stringified JavaScript sources).

**Comment by mgedmin** [comment]
This error goes away if I create the `_design/widget` document manually.
