### ISSUE TITLE
/votings widget fails to work (a 2nd AJAX request also returns 500)

### ISSUE THREAD

**Issue by mgedmin** [ManoSeimas/manoseimas.lt#78]
This is not a duplicate of #77.

The error is
```
Internal Server Error: /0002zq.json
Traceback (most recent call last):
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/parts/django-sboard/sboard/views.py", line 70, in node_view
    return view.validate() or view.render()
  File "/vagrant/parts/django-sboard/sboard/nodes.py", line 567, in render
    return json_response(self.node._doc)
  File "/vagrant/parts/django-sboard/sboard/json.py", line 7, in json_response
    content = json.dumps(data)
AttributeError: 'module' object has no attribute 'dumps'
```

Filed upstream as https://bitbucket.org/sirex/django-sboard/issues/1/attributeerror-module-object-has-no

**Comment by mgedmin** [comment]
Uh, actually... don't we use [a fork of django-sboard on GitHub](https://github.com/ManoSeimas/django-sboard)?   Because https://github.com/ManoSeimas/manoseimas.lt/blob/31b6fbb48564e04662c4ac740741ea3f16e89584/config/base.cfg#L12

**Comment by frgtn** [comment]
Yes, it was moved to github under manoseimas org because I needed to fix something and was too lazy to `hg`.

**Comment by mgedmin** [comment]
(Thank you for doing that.)
